CC = gcc
CFLAGS = -Wall -std=c99 -o -g
LDLIBS = -lm


all: input

input.o: input.c input.h 
	$(CC) $(CFLAGS) calc.c base.c operation.c base.h operation.h 

clean:
	rm -f *.o
	rm -f input pattern match
	rm -f 
	rm -f *.h.gch output.txt